name: 民間能源轉型推動聯盟 - Citizen is Energy
description: 能源轉型包含「廢核除煤、能源效率、綠色能源、智慧管理、經濟共享、民主治理」六大面向。2015 年，全台各縣市關切能源轉型的民間團體，組成「能源轉型推動聯盟」，期望推動進步的能源教育，協助中央與地方政府落實能源轉型的計劃。
cover: assets/images/cover.png
favicon: assets/images/

code:
  source: https://github.com/ETBlue/citizenergy
  license: MIT
content: 
  source: 
  license: All rights reserved for Citizen is Energy
data: 
  source: 
  license: 

